services:
  - type: web
    name: tweetapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn TweetApp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4 